# HTML
- task: AzureWebApp@1
  inputs:
    azureSubscription: 'Azure for Students(3fce2a83-6de0-4a74-a86b-73a4a26d10a1)'
    appType: 'webApp'
    appName: 'foodie-blog'
    deployToSlotOrASE: true
    resourceGroupName: 'foodie-blog-rg'
    slotName: 'production'
    package: '$(System.DefaultWorkingDirectory)/**/*.zip'
    deploymentMethod: 'auto'
# Archive your static HTML project and save it with the build record.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(build.sourcesDirectory)'
    includeRootFolder: false
- task: PublishBuildArtifacts@1
